name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AdoptOpenJDK 11 (Ensure AdoptOpenJDK is supported)
      - name: Set up JDK 11 (AdoptOpenJDK)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Correct distribution name

      # Run Maven tests
      - name: Run tests
        run: |
          mvn install
          mvn test
