name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (with distribution specified)
      - name: Set up JDK 11
        uses: actions/setup-java@v2  # Use v2 instead of v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Specify AdoptOpenJDK explicitly

      # Run unit tests using Maven (adjust for your build tool)
      - name: Run tests
        run: |
          mvn install
          mvn test
